### ISSUE TITLE
Domain is not a valid hostname

### ISSUE THREAD

**Issue by pschraml** [brenner-tobias/addon-cloudflared#506] opened 2023-10-13 18:46 UTC
### The problem

 FATAL: 'halabps.icu' is not a valid hostname. Please make sure not to include the protocol (e.g. 'https://') nor the port (e.g. ':8123') and only use lowercase characters in the 'external_hostname'.
No change worked fine before the update.

### What version of Cloudflared has the issue?

4.2.8

### What was the last working version of Cloudflared?

4.2.7

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: halabps.icu
additional_hosts:
  - hostname: halabps.icu
    service: https://xxx.xxx.xxx.xxx:8123
tunnel_name: HomeAssist
```

### Anything in the logs that might be useful for us?

```txt
-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.2.8
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.10.3
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[18:58:30] INFO: Checking add-on config...
[18:58:31] FATAL: 'halabps.icu' is not a valid hostname. Please make sure not to include the protocol (e.g. 'https://') nor the port (e.g. ':8123') and only use lowercase characters in the 'external_hostname'.
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

### Steps to reproduce the issue

No realy

**Comment by skipishere** [comment] 2023-10-13 18:49
Duplicate of #500 , #501 , #502

**Comment by pschraml** [comment] 2023-10-13 18:50
Restored to 4.2.7 and this version is working.

**Comment by jeracom** [comment] 2023-10-13 19:10
I have the same problem!
I'm back to 4.2.7!
FATAL: 'Blub-Bla-Bla.com' is not a valid hostname.....

**Comment by Dex-ctrl** [comment] 2023-10-13 19:11
how did you restore to 4.2.7

**Comment by Benne007** [comment] 2023-10-13 19:12
Same problem with domain ......de

**Comment by jeracom** [comment] 2023-10-13 19:22
> how did you restore to 4.2.7

Because the version is running?

**Comment by Dex-ctrl** [comment] 2023-10-13 19:24
> > how did you restore to 4.2.7
> 
> Because the version is running?

ok i have updated to the newest version which is obviously not working so how do I downgrade to the 4.2.7?

**Comment by jeracom** [comment] 2023-10-13 19:26
> > > how did you restore to 4.2.7
> > 
> > 
> > Because the version is running?
> 
> ok i have updated to the newest version which is obviously not working so how do I downgrade to the 4.2.7?

System -> Backup -> Restore

**Comment by jodewee** [comment] 2023-10-13 19:27
> > > how did you restore to 4.2.7
> > 
> > 
> > Because the version is running?
> 
> ok i have updated to the newest version which is obviously not working so how do I downgrade to the 4.2.7?

System --> backups --> choose the backup of cloudflare addon and Select restore

**Comment by jeracom** [comment] 2023-10-13 19:29
@skipishere And what's your "stupid thumb" down for?

**Comment by skipishere** [comment] 2023-10-13 19:32
> @skipishere And what's your "stupid thumb" down for?

There are currently a number of duplicated issues with lots of 'me too' or '+1', also the description says it previously worked in 4.2.7 so you're not adding any value to the thread. Subscribe to the issue for updates instead, helps keep the issue clear and easier to follow for those of us trying to fix it. 

Not an aggressive thumbs down, just hopefully a teaching one.

**Comment by brenner-tobias** [comment] 2023-10-13 20:03
Thanks for raining this and sorry for this bug. I have reverted to the old regex with addition of äöüß, so it should work in the next release.
Can you please share your domain name layout, so I can check why the suggested regex was not working for you and come up with a more elegant solution?

**Comment by brenner-tobias** [comment] 2023-10-13 20:04
Should be fixed in [4.2.9](https://github.com/brenner-tobias/addon-cloudflared/releases/tag/v4.2.9), please check and confirm

**Comment by jtoland11** [comment] 2023-10-13 20:09
Its working now thank you, sad that it seems /\p{L} doesn't work 👍

**Comment by brenner-tobias** [comment] 2023-10-13 20:12
I have to be honest: no idea why this did not work. I checked with multiple domains, plus it was working for me in the Edge release with multiple subdomains, also no issues from other edge users for a day.
Anyways, again sorry, will look into it in detail

**Closed by brenner-tobias** 2023-10-13 20:12 UTC

**Comment by pschraml** [comment] 2023-10-13 20:48
> how did you restore to 4.2.7

From my backup 😄

**Comment by RedruthXD** [comment] 2023-10-13 20:55
4.2.9 IT WORKS
