### ISSUE TITLE
Tunnel with name already exists

### ISSUE THREAD

**Issue by iosoft** [brenner-tobias/addon-cloudflared#99] opened 2022-05-21 09:33 UTC
**Describe the bug**
I use a Cable Internet connection. Sometimes connection gets cut for few minutes or seconds.
I have noticed that, in some _rear cases_, this plugin stops working totally. Can't create the tunnel any more.
Device restart or Add-on restart doesn't work!
**I need to Delete the Tunnel from dash.teams.cloudflare.com and then restart the Add-on/Full Device to restart the tunnel.**

**Log Error Message**
> FATAL: Failed to create tunnel. Please check the Cloudflare Teams Dashboard for an existing tunnel with the name homeassistant and delete it: https://dash.teams.cloudflare.com/ Access / Tunnels.

**Expected behavior**
It should re-establish the broken connection/tunnel automatically.
Pls fix this annoying bug for this 99.99999% perfect Add-on.

**Add-On / Home Assistant Information (please complete the following information):**
- Add-On Version (2.0.0) latest
- Supervisor Version (2022.05.2)
- Core Version (2022.5.5)
- Operating System (e.g. Home Assistant OS 8.1)
- Devices (e.g. Raspberry Pi 3 Model B)

**Log**

> [cont-init.d] 10-cloudflared-config.sh: executing... 
> failed to create tunnel: Create Tunnel API call failed: tunnel with name already exists
> [14:57:49] FATAL: Failed to create tunnel.
>     Please check the Cloudflare Teams Dashboard for an existing tunnel with the name homeassistant and delete it:
>     https://dash.teams.cloudflare.com/ Access / Tunnels
> [cont-init.d] 10-cloudflared-config.sh: exited 1.
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] 99-message.sh: executing... 
> -----------------------------------------------------------
>                 Oops! Something went wrong.
> 
>  We are so sorry, but something went terribly wrong when
>  starting or running this add-on.
>  
>  Be sure to check the log above, line by line, for hints.
> -----------------------------------------------------------
> [cont-finish.d] 99-message.sh: exited 0.

**Comment by dutch-erik** [comment] 2022-05-21 19:34
Same here:
`Error 1033  Ray ID: 70efb6c62d39422a • 2022-05-21 19:28:13 UTC
Argo Tunnel error `

`[21:28:09] INFO: Creating new tunnel...
failed to create tunnel: Create Tunnel API call failed: tunnel with name already exists
[21:28:15] FATAL: Failed to create tunnel.
    Please check the Cloudflare Teams Dashboard for an existing tunnel with the name homeassistant and delete it:
    https://dash.teams.cloudflare.com/ Access / Tunnels
[cont-init.d] 10-cloudflared-config.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.

 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting. `

**Comment by elcajon** [comment] 2022-05-22 08:39
Could you provide some more information on the add-on configuration from supervisor page? 
Also please provide a log excerpt with log level set to `debug`.

I need to be able to recreate the error somehow.

**Comment by dutch-erik** [comment] 2022-05-22 11:14
Below the configuration (which didn’t change btw)?

additional_hosts:
  - hostname: nas.domein.net
    service: https://192.168.2.210:5001
external_hostname: ha.domein.net
tunnel_name: homeassistant
tunnel_token: ''
data_folder: ssl


How can I provide you with the debug information?
This way?

logger:
  default: warning
  logs:
    custom_component.cloudflared: debug

**Comment by dutch-erik** [comment] 2022-05-22 11:30
Log is now set as debug:

`Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-cloudflared-config.sh: executing... 
[13:27:02] INFO: Data path set to /ssl/cloudflared
[13:27:02] INFO: Checking Add-on config...
[13:27:04] DEBUG: Checking host {"hostname":"nas.domein.net","service":"https://192.168.2.210:5001"}...
[13:27:06] INFO: Checking for existing certificate...
[13:27:06] INFO: Existing certificate found
[13:27:06] INFO: Checking for existing tunnel...
[13:27:06] NOTICE: No tunnel file found
[13:27:06] INFO: Creating new tunnel...
failed to create tunnel: Create Tunnel API call failed: tunnel with name already exists
[13:27:27] FATAL: Failed to create tunnel.
    Please check the Cloudflare Teams Dashboard for an existing tunnel with the name homeassistant and delete it:
    https://dash.teams.cloudflare.com/ Access / Tunnels
[cont-init.d] 10-cloudflared-config.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal. `

**Comment by dutch-erik** [comment] 2022-05-22 11:42
Looks like there isn’t much useful in the debug log, so I created new tunnel(name) wich is working fine again. 😉

**Comment by elcajon** [comment] 2022-05-22 14:01
The add-on looks for the tunnel configuration file `/ssl/cloudflared/tunnel.json` does this file exist?
The error from the logs seem to be caused of the file missing or renamed.

**Comment by dutch-erik** [comment] 2022-05-22 19:00
The file `/ssl/cloudflared/tunnel.json` does exist, however by creating a new tunnel via this addon I think I can't figure out anymore what happened before. I'll come back when this happens again for me.

**Comment by iosoft** [comment] 2022-05-23 02:39
Yes, this is a rear random bug.

**Comment by elcajon** [comment] 2022-05-23 06:21
If the issue occurs again, please have a look at the tunnel.json file. The add-on only tries to create a new tunnel if this file is missing.

**Comment by iosoft** [comment] 2022-05-29 03:16
Hello, last night we had thunder storm. So, the Internet was up and down multiple times. When finally fully restored, the Cloudflare Tunnel is still down since then. Says error at log - 

> Failed to create tunnel. Please check the Cloudflare Teams Dashboard for an existing tunnel with the name homeassistant and delete it

Pls let me know if you if you need any detailed information.
I am keep it in this state for you to debug.


**FULL LOG:**

```
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 00-cloudflared-log.sh: executing... 
[cont-init.d] 00-cloudflared-log.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-cloudflared-config.sh: executing... 
[08:42:10] INFO: Checking Add-on config...
[08:42:15] INFO: Checking for existing certificate...
[08:42:15] INFO: Existing certificate found
[08:42:15] INFO: Checking for existing tunnel...
[08:42:15] NOTICE: No tunnel file found
[08:42:15] INFO: Creating new tunnel...
failed to create tunnel: Create Tunnel API call failed: tunnel with name already exists
[08:42:17] FATAL: Failed to create tunnel.
    Please check the Cloudflare Teams Dashboard for an existing tunnel with the name homeassistant and delete it:
    https://dash.teams.cloudflare.com/ Access / Tunnels
[cont-init.d] 10-cloudflared-config.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by iosoft** [comment] 2022-05-29 03:16
> If the issue occurs again, please have a look at the tunnel.json file. The add-on only tries to create a new tunnel if this file is missing.

where/how to check?

**Comment by iosoft** [comment] 2022-05-29 03:25
### UPDATE

When I set the Log Level to 'trace', I get this log where it says -

> [08:51:48] INFO: Checking for existing tunnel...
> [08:51:48] TRACE: bashio::fs.file_exists: /data/tunnel.json
> [08:51:48] NOTICE: No tunnel file found
> [08:51:48] TRACE: createTunnel
> [08:51:48] INFO: Creating new tunnel...
> failed to create tunnel: Create Tunnel API call failed: tunnel with name already exists

**FULL LOG:**

> [08:55:10] TRACE: bashio::var.true: null
> [08:55:10] TRACE: hasCertificate
> [08:55:10] INFO: Checking for existing certificate...
> [08:55:10] TRACE: bashio::fs.file_exists: /data/cert.pem
> [08:55:10] INFO: Existing certificate found
> [08:55:10] TRACE: hasTunnel:
> [08:55:10] INFO: Checking for existing tunnel...
> [08:55:10] TRACE: bashio::fs.file_exists: /data/tunnel.json
> [08:55:10] NOTICE: No tunnel file found
> [08:55:10] TRACE: createTunnel
> [08:55:10] INFO: Creating new tunnel...
> failed to create tunnel: Create Tunnel API call failed: tunnel with name already exists
> [08:55:12] TRACE: bashio::exit.nok: Failed to create tunnel.
>     Please check the Cloudflare Teams Dashboard for an existing tunnel with the name homeassistant and delete it:
>     https://dash.teams.cloudflare.com/ Access / Tunnels
> [08:55:12] TRACE: bashio::var.has_value: Failed to create tunnel.
>     Please check the Cloudflare Teams Dashboard for an existing tunnel with the name homeassistant and delete it:
>     https://dash.teams.cloudflare.com/ Access / Tunnels
> [08:55:12] FATAL: Failed to create tunnel.
>     Please check the Cloudflare Teams Dashboard for an existing tunnel with the name homeassistant and delete it:
>     https://dash.teams.cloudflare.com/ Access / Tunnels
> [cont-init.d] 10-cloudflared-config.sh: exited 1.
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] 99-message.sh: executing... 
> -----------------------------------------------------------
>                 Oops! Something went wrong.
> 
>  We are so sorry, but something went terribly wrong when
>  starting or running this add-on.
>  
>  Be sure to check the log above, line by line, for hints.
> -----------------------------------------------------------
> [cont-finish.d] 99-message.sh: exited 0.
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.

**Comment by elcajon** [comment] 2022-05-29 09:14
I do not know how to recreate the error. In principle, the problem can only occur when the tunnel.json file is missing. 

What you can do is switching from [local to remote managed tunnel](https://github.com/brenner-tobias/addon-cloudflared/blob/main/docs/tunnels.md).

**Comment by iosoft** [comment] 2022-05-29 12:22
I understand this stupid, complex and rear issue.
I don't understand why tunnel.json not found!!! permission error?! path error?!!

Can I suggest a 'work around' or exception handling?

Add a checking condition that if the file tunnel.json doesn't exists AND tunnel with name already exists, it will delete the Cloudflare tunnel and retry to establish the connection.

**Comment by iosoft** [comment] 2022-05-29 12:27
I think this rear error is happening since you changed the save path for data and certificate files. Might be wrong....
May be you should keep two copies of these file(s) in new path and old path and check both....

**Comment by iosoft** [comment] 2022-05-29 12:48
> I do not know how to recreate the error.

may be, turn off and on your Internet router multiple times in 2 mins interval 😛

**Comment by elcajon** [comment] 2022-05-29 12:58
> I understand this stupid, complex and rear issue. I don't understand why tunnel.json not found!!! permission error?! path error?!!

Could you create a backup of the add-on, download and extract it and check if the tunnel.json is missing?

> Can I suggest a 'work around' or exception handling?
> 
> Add a checking condition that if the file tunnel.json doesn't exists AND tunnel with name already exists, it will delete the Cloudflare tunnel and retry to establish the connection.

Deleting an existing tunnel isn't possible from the cloudflared binary, nevertheless I wouldn't automatically delete a tunnel as it could be in use on some other host machines beside Home Assistant.

> I think this rear error is happening since you changed the save path for data and certificate files. Might be wrong....
> May be you should keep two copies of these file(s) in new path and old path and check both....

The path didn't really change. We save everything inside /data as default for HA add-ons. Path can be changed with add-on configuration option to /ssl, /share or /config. I rechecked the related code and can't find any issues. 
Keeping duplicates of the same files wouldn't help. 


> > I do not know how to recreate the error.
> 
> may be, turn off and on your Internet router multiple times in 2 mins interval 😛

I do not think I will do that 😉

**Comment by iosoft** [comment] 2022-05-29 13:23
Just downloaded the backup, no tunnel.json
Backup includes -

- addon.json
- apparmor
- backup.json
- data/cert.pem
- data/config.json
- data/options.json

**Comment by iosoft** [comment] 2022-06-03 01:59
Same error last night.
tunnel.json not found!

**Comment by iosoft** [comment] 2022-07-03 17:22
nope, bug still exists but rear.

**Comment by brenner-tobias** [comment] 2022-07-05 20:34
I have no clue, I also search through the code multiple times and did re-installs and even disconnected my router... so if anyone who has the problem can please confirm that they did a complete reset of the add-on by setting the option `reset_cloudflared_files=true` and after that does a simple clean installation.
If this still happens, we need as many details about the config, the system and the loggin with log-level "debug" as possible here to reproduce this.

**Comment by elcajon** [comment] 2022-07-25 18:54
Are there any new findings on this? If not, I would close the issue because we can't recreate the bug without more information.

**Comment by iosoft** [comment] 2022-07-26 15:00
**Yes, the issue still exists, but I made a bypass.**

I wrote a small script that runs on auto-start of HA.
It checks if tunnel.json file exists, if not restore a copy from tunnel.json.bkp

Since then, I faced no such problem.

**Comment by RaptorHunterMZ** [comment] 2022-07-29 01:37
> **Yes, the issue still exists, but I made a bypass.**
> 
> I wrote a small script that runs on auto-start of HA. It checks if tunnel.json file exists, if not restore a copy from tunnel.json.bkp
> 
> Since then, I faced no such problem.
> 
> **SUGGESTION**: can you pls put similar logic in your add-on?

I have the same issue can you explain how you created the script to this. 

BTW:
1. I am using an old Desktop for HomeAssistant, might this be the cause for this problem?
2. I have also noted that after restarting sometimes the add-on doesn't seem to start correctly usually missing the the icon and the Documentation tab.

**Comment by iosoft** [comment] 2022-07-29 03:29
> I have the same issue can you explain how you created the script to this.
Sure. Are you using Node-RED add-on?

> 1. I am using an old Desktop for HomeAssistant, might this be the cause for this problem?
That is not the problem.

> 2. I have also noted that after restarting sometimes the add-on doesn't seem to start correctly usually missing the the icon and the Documentation tab.
Sorry, I never faced this problem.

**Just a suggestion**: Have enough RAM and a SSD for the OS.

**Comment by Andalaosa** [comment] 2022-08-01 23:21
Hola, después de muchos intentos, funcionar nuevamente.  Cambiando el nombre del túnel desde la configuración del addon.

Hello, after many attempts, work again. Renaming the tunnel from the addon settings.

![2022-08-01 20_18_08-Home Assistant](https://user-images.githubusercontent.com/60817880/182261218-c08d7295-5f84-4142-a110-0b3cdfdfe5f2.png)

**Comment by Andalaosa** [comment] 2022-08-01 23:33
> Hola, después de muchos intentos, funcionar nuevamente. Cambiando el nombre del túnel desde la configuración del addon.
> 
> Hello, after many attempts, work again. Renaming the tunnel from the addon settings.
> 
> ![2022-08-01 20_18_08-Home Assistant](https://user-images.githubusercontent.com/60817880/182261218-c08d7295-5f84-4142-a110-0b3cdfdfe5f2.png)

Error:

17:26:58] INFO: Creating new tunnel...
failed to create tunnel: Create Tunnel API call failed: tunnel with name already exists
[17:26:59] FATAL: Failed to create tunnel.
    Please check the Cloudflare Teams Dashboard for an existing tunnel with the name **homeassistant** and delete it:
    https://dash.teams.cloudflare.com/ Access / Tunnels
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1

**Comment by elcajon** [comment] 2022-08-03 16:37
With #132 merged I am closing this for the time beeing. If the error occurs again, please fill a new Issue with as lot of details as possible.

**Closed by elcajon** 2022-08-03 16:37 UTC
Labels: help-wanted
