### ISSUE TITLE
Same situation

### ISSUE THREAD

**Issue by Hummelchen01** [brenner-tobias/addon-cloudflared#502] opened 2023-10-13 18:13 UTC
### The problem

2 Home-Assistant Systems are involved. The other are informed not updating from 4.2.7 -> 4.2.8.
I hope for a quick fix.

Thanks

### What version of Cloudflared has the issue?

4.2.8

### What was the last working version of Cloudflared?

4.2.7

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Hostname with small characters and a point. xxxxxxxxxx.work / xxxxxxx-xxxxx.work

**Comment by BrammyS** [comment] 2023-10-13 18:13
Experiencing the same issue :)

**Comment by MattCheetham** [comment] 2023-10-13 18:17
Duplicate of #500 and #501

**Comment by brenner-tobias** [comment] 2023-10-13 19:57
Thanks for raining this and sorry for this bug. I have reverted to the old regex with addition of äöüß, so it should work in the next release.
Can you please share your domain name layout, so I can check why the suggested regex was not working for you and come up with a more elegant solution?

**Comment by brenner-tobias** [comment] 2023-10-13 20:04
Should be fixed in [4.2.9](https://github.com/brenner-tobias/addon-cloudflared/releases/tag/v4.2.9), please check and confirm

**Comment by brenner-tobias** [comment] 2023-10-13 20:14
I have to be honest: no idea why this did not work. I checked with multiple domains, plus it was working for me in the Edge release with multiple subdomains, also no issues from other edge users for a day.
Anyways, again sorry, will look into it in detail

**Closed by brenner-tobias** 2023-10-13 20:14 UTC
