### ISSUE TITLE
not a valid hostname after update

### ISSUE THREAD

**Issue by Imnotcreativesoicantthinkofaname** [brenner-tobias/addon-cloudflared#501] opened 2023-10-13 17:05 UTC
### The problem

Did the setup today. After i was done and all running i saw there is a new update. I did run the update and got the error code in the title (and down in the logs)

### What version of Cloudflared has the issue?

4.2.8

### What was the last working version of Cloudflared?

one before

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: vanhulle.pro
additional_hosts: []
```

### Anything in the logs that might be useful for us?

```txt
-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.2.8
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.10.3
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[18:58:23] INFO: Checking add-on config...
[18:58:23] FATAL: 'vanhulle.pro' is not a valid hostname. Please make sure not to include the protocol (e.g. 'https://') nor the port (e.g. ':8123') and only use lowercase characters in the 'external_hostname'.
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

### Steps to reproduce the issue

im not able to install the previous versions, may be because of skill issue but cant test. I just now that it worked before the update and i copied my domain name (and checked for html at the front and port at the end etc)

### Additional information

thanks for your work

**Comment by djfanatix** [comment] 2023-10-13 17:10
Yep, same issue over here

**Comment by diogopms** [comment] 2023-10-13 17:24
I'm having the same issue..

**Comment by Herzblut21** [comment] 2023-10-13 17:31
Bei mir auch, Backup zurückgespielt und ales geht wieder.

**Comment by dmartella** [comment] 2023-10-13 17:35
Hi, same issue here
Thanks

**Comment by g33kt00l** [comment] 2023-10-13 17:39
hi, same here, thanks

**Comment by Olof007** [comment] 2023-10-13 17:43
Same issue. Was working perfectly before the upgrade. Same error in the log as first post.
An nslookup provide a valid DNS answer.

**Comment by mrhelder** [comment] 2023-10-13 17:50
Same here. Hoping for a quick fix!

**Comment by cjmjmartens** [comment] 2023-10-13 17:50
Same error message after updating to 4.2.8

**Comment by elyobelyob** [comment] 2023-10-13 17:50
Same issue. "FATAL: 'ha.xxxxxx.com' is not a valid hostname."

**Comment by mrhelder** [comment] 2023-10-13 17:53
Backup saved the day! Restored from the backup created just prior to the update, and all is working

**Comment by MattCheetham** [comment] 2023-10-13 17:54
Same here.

**Comment by PathVirdae** [comment] 2023-10-13 17:57
same, pathv.net. Working fine before

**Comment by adam-kulik** [comment] 2023-10-13 17:58
Same here

**Comment by Camatobe** [comment] 2023-10-13 17:59
same issue:
to track things down, my url is: homeassistant.xxxx-xxxxxx.de 
no numbers, no umlaute, no uppercase, just a subdomain with normal letters and a dash in between the domain.

**Comment by Toolhead** [comment] 2023-10-13 18:06
Same here.

**Comment by svanimpelen** [comment] 2023-10-13 18:08
Same Issue

**Comment by PedroMRP** [comment] 2023-10-13 18:09
@brenner-tobias

**Comment by flufftronix** [comment] 2023-10-13 18:12
I don't know how to write regex, but I see that the previous version's expression

`^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$`

produces a hit when tested with test.domain.com at [regexr.com](https://regexr.com/), however that doesn't work with the latest version's updated expression:

`^(([\p{Ll}\p{Nd}]|[\p{Ll}\p{Nd}][\p{Ll}\p{Nd}\-]*[\p{Ll}\p{Nd}])\.)+([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$`

**Comment by pem884** [comment] 2023-10-13 18:13
Thank you @flufftronix 
Another user posted a similar mention in #500, I know moderate amounts of regex and am diving into it until/unless someone else who knows better can jump in :)

**Comment by riccardo1991** [comment] 2023-10-13 18:16
I am encountering the same problem

**Comment by Remcovf** [comment] 2023-10-13 18:18
Same issue here!

**Comment by Camatobe** [comment] 2023-10-13 18:21
This regex is working for me.
I don't know much about more test-urls or more umlaute you want to support, but it works on https://regex101.com/ with all flavors.
maybe it helps?

`^(([a-z0-9äöü]|[a-z0-9äöü][a-z0-9äöü\-]*[a-z0-9äöü])\.)+([a-z0-9äöü]|[a-z0-9äöü][a-z0-9äöü\-]*[a-z0-9äöü])$`

**Comment by flufftronix** [comment] 2023-10-13 18:34
> This regex is working for me. I don't know much about more test-urls or more umlaute you want to support, but it works on https://regex101.com/ with all flavors. maybe it helps?
> 
> `^(([a-z0-9äöü]|[a-z0-9äöü][a-z0-9äöü\-]*[a-z0-9äöü])\.)+([a-z0-9äöü]|[a-z0-9äöü][a-z0-9äöü\-]*[a-z0-9äöü])$`

This might be what we're looking for:

`^(([a-z0-9äöü]|[a-z0-9][a-z0-9äöü\-]*[a-z0-9])\.)+([a-z0-9]|[a-z0-9][a-z0-9]*[a-z0-9])$`

It's allowing umlaut on the subdomain but not the TLD or suffix. Works with `pöp.pöp.example.com` too.

**Comment by Jasom00** [comment] 2023-10-13 18:38
Same issue here!

**Comment by vquie** [comment] 2023-10-13 18:40
Who needs umlaut Domains anyway? :-D

This regex could work.
```
"^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])$"
```

**Comment by lkwr** [comment] 2023-10-13 18:43
> > This regex is working for me. I don't know much about more test-urls or more umlaute you want to support, but it works on https://regex101.com/ with all flavors. maybe it helps?
> > `^(([a-z0-9äöü]|[a-z0-9äöü][a-z0-9äöü\-]*[a-z0-9äöü])\.)+([a-z0-9äöü]|[a-z0-9äöü][a-z0-9äöü\-]*[a-z0-9äöü])$`
> 
> This might be what we're looking for:
> 
> `^(([a-z0-9äöü]|[a-z0-9][a-z0-9äöü\-]*[a-z0-9])\.)+([a-z0-9]|[a-z0-9][a-z0-9]*[a-z0-9])$`
> 
> It's allowing umlaut on the subdomain but not the TLD or suffix. Works with `pöp.pöp.example.com` too.

We don't need a special regex for umlaute, simply use IDN format (https://www.punycoder.com/) which is work fine on the version before the regex change

**Comment by flufftronix** [comment] 2023-10-13 18:53
I don't use umlauts in domain names myself, so either fix works for me

**Comment by jodewee** [comment] 2023-10-13 19:28
Is there a workaround, or do we have to restore the backup and Wait for a proper fix?

**Comment by PedroMRP** [comment] 2023-10-13 19:29
> Is there a workaround, or do we have to restore the backup and Wait for a proper fix?

For now you should restore the backup

**Comment by nstiller** [comment] 2023-10-13 19:39
> > Is there a workaround, or do we have to restore the backup and Wait for a proper fix?
> 
> For now you should restore the backup

![Restore from backup](https://github.com/brenner-tobias/addon-cloudflared/assets/6173496/202509db-185c-4ac3-ad41-cccee5848cca)

Thanks, the restore back to 4.2.7 worked for me. Also, I turned off the "Auto update the add-on when there is a new version available" option in the cloudflared add-on after restoring, for now at least.

**Comment by elyobelyob** [comment] 2023-10-13 19:55
Should there be a more robust release cycle for crucial add-ons, or even all of them. Some sort of beta process. I know it’s voluntary work and very much appreciated. The main body of work that this update addresses is niche.On 13 Oct 2023, at 20:39, Nate Stiller ***@***.***> wrote:﻿


Is there a workaround, or do we have to restore the backup and Wait for a proper fix?

For now you should restore the backup


Thanks, the restore back to 4.2.7 worked for me. Also, I turned off the "Auto update the add-on when there is a new version available" option in the cloudflared add-on after restoring, for now at least.

**Comment by brenner-tobias** [comment] 2023-10-13 19:58
Thanks for raining this and sorry for this bug. I have reverted to the old regex with addition of äöüß, so it should work in the next release.
Can you please share your domain name layout, so I can check why the suggested regex was not working for you and come up with a more elegant solution?

**Comment by brenner-tobias** [comment] 2023-10-13 20:05
Should be fixed in [4.2.9](https://github.com/brenner-tobias/addon-cloudflared/releases/tag/v4.2.9), please check and confirm

**Comment by PedroMRP** [comment] 2023-10-13 20:08
> Should be fixed in [4.2.9](https://github.com/brenner-tobias/addon-cloudflared/releases/tag/v4.2.9), please check and confirm

Confirmed that is now working

**Comment by Olof007** [comment] 2023-10-13 20:09
Indeed, working again. Thanks for the quick fix

**Comment by nstiller** [comment] 2023-10-13 20:12
> Should be fixed in [4.2.9](https://github.com/brenner-tobias/addon-cloudflared/releases/tag/v4.2.9), please check and confirm

Upgrading 4.2.7 -> 4.2.9...
![Upgrading 4.2.7 -> 4.2.9](https://github.com/brenner-tobias/addon-cloudflared/assets/6173496/f90caaf0-30d7-4e14-b06f-4ce448b50bbc)

... and works! Thank you @brenner-tobias 

```
-----------------------------------------------------------
 Add-on: Cloudflared
 Use a Cloudflare Tunnel to remotely connect to Home Assistant without opening any ports
-----------------------------------------------------------
 Add-on version: 4.2.9
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.10.2
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[13:08:04] INFO: Checking add-on config...
[13:08:07] INFO: Checking for existing certificate...
[13:08:07] INFO: Existing certificate found
[13:08:07] INFO: Checking for existing tunnel...
[13:08:07] INFO: Existing tunnel with ID b3473ee2-88ad-44cc-949b-xxxxxx found
[13:08:07] INFO: Checking if existing tunnel matches name given in config
[13:08:08] INFO: Existing Cloudflare Tunnel name matches config, proceeding with existing tunnel file
[13:08:08] INFO: Creating config file...
[13:08:13] INFO: Validating config file...
Validating rules from /tmp/config.json
OK
[13:08:14] INFO: Creating DNS entry mydomain.com...
2023-10-13T20:08:15Z INF mydomain.com is already configured to route to your tunnel tunnelID=b3473ee2-88ad-44cc-949b-xxxxxx
[13:08:15] INFO: Finished setting up the Cloudflare Tunnel
[13:08:16] INFO: Connecting Cloudflare Tunnel...
2023-10-13T20:08:16Z INF Starting tunnel tunnelID=b3473ee2-88ad-44cc-949b-xxxxxx
2023-10-13T20:08:16Z INF Version 2023.8.2
2023-10-13T20:08:16Z INF GOOS: linux, GOVersion: go1.20.6, GoArch: arm64
2023-10-13T20:08:16Z INF Settings: map[config:/tmp/config.json cred-file:/data/tunnel.json credentials-file:/data/tunnel.json loglevel:info metrics:0.0.0.0:36500 no-autoupdate:true origincert:/data/cert.pem]
2023-10-13T20:08:16Z INF Generated Connector ID: 1ac76c2d-1cb5-476d-8ab1-xxxxxxx
2023-10-13T20:08:17Z INF Initial protocol quic
2023-10-13T20:08:17Z INF ICMP proxy will use 172.30.33.4 as source for IPv4
2023-10-13T20:08:17Z INF ICMP proxy will use :: as source for IPv6
2023-10-13T20:08:17Z INF Starting metrics server on [::]:36500/metrics
2023-10-13T20:08:17Z INF Registered tunnel connection connIndex=0 connection=12f66f40-0ee3-47cb-b8ad-xxxx event=0 ip=198.41.200.x location=sjc08 protocol=quic
2023-10-13T20:08:18Z INF Registered tunnel connection connIndex=1 connection=a9292d35-f9dd-4876-91cc-xxxx event=0 ip=198.41.192.x location=lax06 protocol=quic
2023-10-13T20:08:18Z INF Registered tunnel connection connIndex=2 connection=c5fa4301-071a-4f8b-b77c-xxxx event=0 ip=198.41.192.x location=lax08 protocol=quic
2023-10-13T20:08:19Z INF Registered tunnel connection connIndex=3 connection=61938f46-99bf-4925-a41a-xxxx event=0 ip=198.41.200.x location=sjc05 protocol=quic
```

**Comment by brenner-tobias** [comment] 2023-10-13 20:14
I have to be honest: no idea why this did not work. I checked with multiple domains, plus it was working for me in the Edge release with multiple subdomains, also no issues from other edge users for a day.
Anyways, again sorry, will look into it in detail

**Closed by brenner-tobias** 2023-10-13 20:14 UTC

**Comment by elyobelyob** [comment] 2023-10-13 23:26
I hope my comments weren't against the amazing efforts you have made. I love this.
