### ISSUE TITLE
Unable to connect remotely after 4.1.7

### ISSUE THREAD

**Issue by nazeg** [brenner-tobias/addon-cloudflared#408] opened 2023-06-04 16:18 UTC
### The problem

Hi, i'm not sure if the problem is version 4.1.7 but i can't connect remotely anymore after upgrade Cloudlfared app. I don't see any error on Cloudflared logs and can connect Homeassistant locally without any problem. Here's the logs:

[12:44:54] INFO: Checking add-on config...
[12:44:58] INFO: Checking for existing certificate...
[12:44:58] INFO: Existing certificate found
[12:44:58] INFO: Checking for existing tunnel...
[12:44:58] INFO: Existing tunnel with ID *************ccf found
[12:44:58] INFO: Checking if existing tunnel matches name given in config
[12:45:00] INFO: Existing Cloudflare Tunnel name matches config, proceeding with existing tunnel file
[12:45:00] INFO: Creating config file...
[12:45:05] INFO: Validating config file...
Validating rules from /tmp/config.json
OK
[12:45:05] INFO: Creating DNS entry ********...
2023-06-04T09:45:07Z INF ******* is already configured to route to your tunnel tunnelID=**********ccf
[12:45:08] INFO: Finished setting up the Cloudflare Tunnel
[12:45:08] INFO: Connecting Cloudflare Tunnel...
2023-06-04T09:45:08Z INF Starting tunnel tunnelID=*********ccf
2023-06-04T09:45:08Z INF Version 2023.5.1
2023-06-04T09:45:08Z INF GOOS: linux, GOVersion: go1.19.6, GoArch: arm64
2023-06-04T09:45:08Z INF Settings: map[config:/tmp/config.json cred-file:/data/tunnel.json credentials-file:/data/tunnel.json loglevel:info metrics:0.0.0.0:36500 no-autoupdate:true origincert:/data/cert.pem]
2023-06-04T09:45:08Z INF Generated Connector ID: ***********d3c
2023-06-04T09:45:08Z INF Initial protocol quic
2023-06-04T09:45:08Z INF ICMP proxy will use 172.**.**.2 as source for IPv4
2023-06-04T09:45:08Z INF ICMP proxy will use :: as source for IPv6
2023-06-04T09:45:09Z INF Starting metrics server on [::]:36500/metrics
2023-06-04T09:45:09Z INF Registered tunnel connection connIndex=0 connection=*************9ab event=0 ip=198.***.***.73 location=FCO protocol=quic
2023-06-04T09:45:09Z INF Updated to new configuration config="{\"ingress\":[{\"hostname\":\"******\", \"originRequest\":{\"noTLSVerify\":true}, \"service\":\"https://homeassistant:2053\"}, {\"originRequest\":{\"noTLSVerify\":true}, \"service\":\"http_status:404\"}], \"warp-routing\":{\"enabled\":false}}" version=1
2023-06-04T09:45:10Z INF Registered tunnel connection connIndex=1 connection=***************5531 event=0 ip=198.***.***.167 location=IST protocol=quic
2023-06-04T09:45:11Z INF Registered tunnel connection connIndex=2 connection=*****************19abe81 event=0 ip=198.******.107 location=IST protocol=quic
2023-06-04T09:45:11Z INF Registered tunnel connection connIndex=3 connection=************39a07b3 event=0 ip=198.***.***.23 location=FCO protocol=quic

### What version of Cloudflared has the issue?

4.1.7

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Hi, i'm not sure if the problem is version 4.1.7 but i can't connect remotely anymore after upgrade Cloudlfared app. I don't see any error on Cloudflared logs and can connect Homeassistant locally without any problem.

**Comment by bossben8** [comment] 2023-06-04 17:19
Cloudflared版本更新到4.1.7後無法訪問網頁

描述錯誤
檢查日誌：未能充分增加接收緩衝區大小（原為：208 kiB，需要：2048 kiB，得到：416 kiB）。有關詳細信息，請參閱https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size 。

預期行為
升級到最新版本4.1.7後，無法訪問網頁。檢查日誌：未能充分增加接收緩衝區大小（原為：208 kiB，需要：2048 kiB，得到：416 kiB）。有關詳細信息，請參閱https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size 。但是之前的版本沒有這個錯誤

Add-On / Home Assistant Information（請填寫以下信息）：
當前版本：4.1.7
supervisor-2023.05.dev1702
core-2023.5.4
Home Assistant Supervised
Raspberry Pi 3 Model B+

**Comment by bossben8** [comment] 2023-06-04 17:22
Unable to access the webpage after the Cloudflared version is updated to 4.1.7

description error
Checking logs: Failed to increase receive buffer size sufficiently (was: 208 kiB, needed: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.

expected behavior
After upgrading to the latest version 4.1.7, the webpage cannot be accessed. Checking logs: Failed to increase receive buffer size sufficiently (was: 208 kiB, needed: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details. But the previous version didn't have this error

Add-On / Home Assistant Information (please fill in the following information):
Current version: 4.1.7
supervisor-2023.05.dev1702
core-2023.5.4
Home Assistant Supervised
Raspberry Pi 3 Model B+

**Comment by lucas685** [comment] 2023-06-04 19:00
Same problem here

**Comment by younesetre** [comment] 2023-06-04 19:42
i have same probleme
2023-06-04T19:02:34Z INF Registered tunnel connection connIndex=0 connection=xxxxxxxxxxxxxxxxxxxxxxxb39-9a51-3dacexxxxx event=0 ip=198.xx.xx.xx location=ALG protocol=quic
2023-06-04T19:02:35Z INF Registered tunnel connection connIndex=1 connection=xxxxxxxxxxxxxxxxx-0bdc8fb2xxxxx event=0 ip=198.198.xx.xx.xx location=MRS protocol=quic
2023-06-04T19:02:35Z INF Registered tunnel connection connIndex=2 connection=xxxxxxxxxxxx-4fc0-8277-a6992xxxxxxxxxxxx event=0 ip=198.198.xx.xx.xx location=ALG protocol=quic
2023-06-04T19:02:36Z INF Registered tunnel connection connIndex=3 connection=xxxxxxxxxxxxxx-4b07-b2c5-1bexxxxxxxxxxx event=0 ip=198.198.xx.xx.xx location=MRS protocol=quic

**Comment by nazeg** [comment] 2023-06-04 19:45
Btw, i tried to back to 4.1.6 but it didn't fix this issue.

**Comment by younesetre** [comment] 2023-06-04 19:50
yes, I tried the same thing but without results
 back to 4.1.6 but it didn't fix this issue.

**Comment by ssdhanas12** [comment] 2023-06-04 20:59
Same here

**Comment by oxymoron1629** [comment] 2023-06-05 01:35
I have the same issue. Changed nothing since the last upgrade. When I go to the external hostname, I just get an "unable to connect".

**Comment by minxhe** [comment] 2023-06-05 05:24
same issue, running into This site:
```
can’t be reachedCheck if there is a typo in domain name..
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by p001710** [comment] 2023-06-05 06:57
Same here!
Die Website ist nicht erreichbar
Die Webseite unter https://xx-xxxx.ga/auth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fxx-xxxxx.ga%2F%3Fauth_callback%3D1&client_id=https%3A%2F%2Fxx-xxxxx.ga%2F&state=eyJoYXNzVXJsIjoiaHR0cHM6Ly9uay1ob21lLmdhIiwiY2xpZW50SWQiOiJodHRwczovL25rLWhvbWUuZ2EvIn0%3D ist eventuell vorübergehend nicht verfügbar oder wurde dauerhaft an eine neue Webadresse verschoben.
ERR_FAILED

**Comment by NopeFinder** [comment] 2023-06-05 08:08
I had the same issue, with the same errors, but starting today I got some new errors:
`2023-06-05T07:59:36Z INF Registered tunnel connection connIndex=0 connection=xxxx-xxxxx-xxxxx xxxxxxxx event=0 ip=xxx.xxx.xxx.xxx location=BRU protocol=quic`
`2023-06-05T07:59:36Z WRN Failed to serve quic connection error="rpc: connection closed" connIndex=1 event=0 ip=xxx.xxx.xxx.xxx`
`2023-06-05T07:59:36Z WRN Register tunnel error from server side error="rpc: connection closed" connIndex=1 event=0 ip=xxx.xxx.xxx.xxx`
`2023-06-05T07:59:37Z INF Retrying connection in up to 2s connIndex=1 event=0 ip=xxx.xxx.xxx.xxx`
`2023-06-05T07:59:38Z INF Registered tunnel connection connIndex=2 connection=xxxxxxxx-xxxxxxxxxxxx event=0 ip=xxx.xxx.xxx.xxx location=AMS protocol=quic`
`2023-06-05T07:59:38Z INF Registered tunnel connection connIndex=3 connection=xxxxxxxx-xxxxxxxxxxxx event=0 ip=xxx.xxx.xxx.xxx location=BRU protocol=quic`
`2023-06-05T07:59:39Z WRN Connection terminated error="rpc: connection closed" connIndex=1`
`2023-06-05T07:59:40Z INF Registered tunnel connection connIndex=1 connection=xxxxx xxxxxx event=0 ip=xxx.xxx.xxx.xxx location=AMS protocol=quic`

**Comment by NopeFinder** [comment] 2023-06-05 08:20
nvm, I'm back to the same logs as before.
`2023-06-05T08:16:55Z INF Registered tunnel connection connIndex=0 connection=xxxxx-xxxxx-xxxxx-xxxxx event=0 ip=xxx.xxx.xxx.xxx location=BRU protocol=quic`
`2023-06-05T08:16:55Z INF Registered tunnel connection connIndex=1 **connection=xxxxx-xxxxx-xxxxx-xxxxx event=0** ip=xxx.xxx.xxx.xxx location=AMS protocol=quic`
`2023-06-05T08:16:57Z INF Registered tunnel connection connIndex=2 connection=xxxxx-xxxxx-xxxxx-xxxxx event=0 ip=xxx.xxx.xxx.xxx location=AMS protocol=quic`
`2023-06-05T08:16:57Z INF Registered tunnel connection connIndex=3 connection=xxxxx-xxxxx-xxxxx-xxxxx event=0 ip=xxx.xxx.xxx.xxx location=BRU protocol=quic`

**Comment by AsafOti** [comment] 2023-06-05 08:24
Same issue

**Comment by zuohaot** [comment] 2023-06-05 08:40
> 

Mine is also from freenom..

**Comment by nazeg** [comment] 2023-06-05 08:42
What's wrong with freenom? Mine is also from there.

**Comment by AsafOti** [comment] 2023-06-05 08:43
Mine also

**Comment by NopeFinder** [comment] 2023-06-05 08:43
mine is as well

**Comment by bossben8** [comment] 2023-06-05 10:51
https://www.home-assistant.io/integrations/cloudflare/
Unusable TLDs
Due to a limitation in the Cloudflare API, you can not use this integration with any of the following TLD’s:

.cf
.ga
.gq
.ml
.tk

**Comment by Lohgerber** [comment] 2023-06-05 10:55
I have the same problem: no more connection to homeassistant over https:// .ga adress

**Comment by nazeg** [comment] 2023-06-05 11:13
> https://www.home-assistant.io/integrations/cloudflare/ Unusable TLDs Due to a limitation in the Cloudflare API, you can not use this integration with any of the following TLD’s:
> 
> .cf .ga .gq .ml .tk

Is this new? We're using without any issue.

**Comment by bednim** [comment] 2023-06-05 19:25
same issue - can't remote in - strangely not even with duckdns :/

**Comment by paki1977** [comment] 2023-06-05 19:29
Hi all, I hope some of you can help me out.. Until a few days ago I used Cloudflare to connect to HA remotely and it worked fine. The day before yesterday I updated the addon to version 4.1.7 and it doesn't start anymore. If I try to start it it gives me the error that I will write to you shortly and the Cloudflare container is automatically stopped.. I tried to uninstall and reinstall but nothing.. I hope for your help.. here is the error:

[17:39:53] ERROR: Something went wrong contacting the API
[17:39:53] ERROR: Something went wrong contacting the API
[17:39:54] INFO: Checking add-on config...
[17:39:54] FATAL: Cannot run without tunnel_token, external_hostname, additional_hosts, catch_all_service or nginx_proxy_manager. Please set at least one of these add-on options.
s6-rc: warning: unable to start service init-cloudflared-config: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.

Has anyone else figured it out and do you know how to fix it? A thousand thanks

**Comment by nazeg** [comment] 2023-06-06 04:17
I bought a new .site domain and it's working without any problem now. I think the limitation of freenom domains is true.

**Comment by bednim** [comment] 2023-06-06 06:57
abandon freenom and get new domain with something like OVH.com - i paid $2 per year - this now works as should.

**Comment by fredfrom** [comment] 2023-06-06 08:47
The cheapest way I have figured out is using a .xyz domain that contains of only numbers. It must be less than 9 numberes. 
It will cost you around 80 cents per year and also renews at 80 cent per year instead of 10$+ per year like most other cheap domains.

I bought on namecheap. Works like a charm. it takese longer though to load if the domain is available. 

The only downside is that you can't pay upfront for more than one year.

**Comment by rvenancio** [comment] 2023-06-06 09:43
just end up buying .win directly from cloudflare, 3.71$ / year.

**Comment by Peertje87** [comment] 2023-06-06 13:14
same here

**Comment by Resident-Rational** [comment] 2023-06-06 18:46
Same issue faced with .ga freenom domain.  Checking cloudflare support forums, ran into below linked post mentioning that .ga TLD is being returned to Gabonese management.  
https://community.cloudflare.com/t/broken-dns-record/517862/6

Tried to register a different TLD at freenom but they seem to have disabled new registrations for now. Below notice appears:

IMPORTANT NOTICE: Because of technical issues the Freenom application for new registrations is temporarily out-of-order.
Please accept our apologies for the inconvenience. We are working on a solution and hope to resume operations shortly.

**Comment by brenner-tobias** [comment] 2023-06-07 21:53
Since this is related to Freenom domains and we raised this quite some time ago, I am closing this issue. Please open a discussion if you want to raise any additional questions regarding this.

**Closed by brenner-tobias** 2023-06-07 21:53 UTC
